### ISSUE TITLE
bitstream

### ISSUE THREAD

**Issue by htprofessor** [OswaldHe/LevelST#8]
excuse me zifan,
 I see the folder named 'bitstream',why there are so many xclbin files,what are their functions.
  could I directly use these xclbin files? which one should I use or should I use all of them to run a program?
  I would appreciate it if you replied to me.
sincerely
Jerry

**Comment by OswaldHe** [comment]
Just use `bitstream/TrigSolver_xilinx_u280_xdma_201920_3_fwd.xclbin`. The rest are for testing incremental improvements of each optimization.
