### ISSUE TITLE
thanks but maybe version is wrong

### ISSUE THREAD

**Issue by htprofessor** [OswaldHe/LevelST#9]
Thanks for your reply,zifan
and I use Vitis 2023.2,my board is xilinx_u280_gen3x16_xdma_1_202211_1,so I need to generate my bitstream right?
![image](https://github.com/OswaldHe/LevelST/assets/103341765/5c536af1-5a15-416b-850b-62016d1cc7f2)
but I cant find  solver.xilinx_u280_xdma_******.hw_generate_bitstream.sh
![image](https://github.com/OswaldHe/LevelST/assets/103341765/ff9a4dc2-6ff0-4957-91cc-7af0d55f02f5)

**Comment by htprofessor** [comment]
![image](https://github.com/OswaldHe/LevelST/assets/103341765/6afcd07b-2ecf-4120-90b3-61caf68d7580)
maybe I need to modify on Autobridge source file,where is the source file 
sorry to bother u,Thanks so much

**Comment by htprofessor** [comment]
after I directly use bash run_tapa.sh.here are the errors
![image](https://github.com/OswaldHe/LevelST/assets/103341765/20f1bf49-4c5d-43c1-bb7a-ae44705b505a)
![image](https://github.com/OswaldHe/LevelST/assets/103341765/4c4fe17a-fd92-44f7-b2ad-73dcf67c5423)
and the contents of my "work.out" folder are
![image](https://github.com/OswaldHe/LevelST/assets/103341765/70c992d4-6805-49c7-80a2-d44fad5258b9)
![image](https://github.com/OswaldHe/LevelST/assets/103341765/0d46d0a0-93a1-42d0-a5b9-378a3b5a9eb5)

**Comment by OswaldHe** [comment]
Hi,

The whole flow only works for TAPA 2022. The most recent version has a significant change so I don't recommend you to use it. Also, it only works for Vitis/Vivado 2021.2, since we're using the old platform. If you're trying the new versions, you probably want to turn off Autobridge, but it may not give you the optimal results.
